apiVersion: v1
kind: Service
metadata:
  name: community-service
  annotations:
    ad.datadoghq.com/nginx.logs: '[{"source":"community-service","service":"community-service"}]'
  labels:
    app: community-service
spec:
  type: ClusterIP
  selector:
    app: community-service
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: http
