version: "3"
services:
  db:
    image: "postgres"
    container_name: "pg_community_service"
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  user_service:
    image: "quay.io/danielmunro/otto-user-service"
    container_name: "otto_user_service"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db