/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"github.com/google/uuid"
	"net/http"
)

type NewPost struct {
	Text       string     `json:"text"`
	User       User       `json:"user"`
	Visibility Visibility `json:"access,omitempty"`
}

func DecodeRequestToNewPost(r *http.Request) *NewPost {
	decoder := json.NewDecoder(r.Body)
	var data *NewPost
	err := decoder.Decode(&data)
	if err != nil {
		panic(err)
	}
	return data
}

func CreateNewPost(userUuid *uuid.UUID, message string) *NewPost {
	return &NewPost{
		Text: message,
		User: User{
			Uuid: userUuid.String(),
		},
	}
}
