/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"github.com/google/uuid"
	"time"
)

type Post struct {
	Uuid *uuid.UUID `json:"uuid"`

	Text string `json:"text,omitempty"`

	User User `json:"user,omitempty"`

	Replies []Reply `json:"replies"`

	Visibility Visibility `json:"visibility,omitempty"`

	Images []Image `json:"images,omitempty"`

	CreatedAt time.Time `json:"created_at"`
}
