/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"github.com/google/uuid"
	"time"
)

type Reply struct {
	Uuid *uuid.UUID `json:"uuid"`

	CreatedAt time.Time `json:"created_at"`

	Post Post `json:"post"`

	Text string `json:"text"`

	User User `json:"user"`
}

func CreateNewReply(userUuid *uuid.UUID, postUuid *uuid.UUID, message string) *NewReply {
	return &NewReply{
		Text: message,
		User: User{
			Uuid: userUuid.String(),
		},
		Post: Post{
			Uuid: postUuid,
		},
	}
}
