/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"log"
	"time"
)

type User struct {
	Uuid string `json:"uuid"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Posts []Post `json:"posts,omitempty"`

	Replies []Reply `json:"replies,omitempty"`

	Follows []Follow `json:"follows,omitempty"`
}

func DecodeMessageToUser(message []byte) *User {
	user := &User{}
	err := json.Unmarshal(message, user)
	if err != nil {
		log.Fatal(err)
	}
	return user
}
