/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"log"
	"time"
)

type User struct {
	Uuid string `json:"uuid"`

	Name string `json:"name"`

	Username string `json:"username"`

	ProfilePic string `json:"profile_pic,omitempty"`

	BioMessage string `json:"bio_message,omitempty"`

	Location string `json:"location,omitempty"`

	Birthday string `json:"birthday,omitempty"`

	Email string `json:"email,omitempty"`

	EmailVerified bool `json:"email_verified,omitempty"`

	Phone string `json:"phone,omitempty"`

	PhoneVerified bool `json:"phone_verified,omitempty"`

	CreatedAt time.Time `json:"created_at"`
}

func DecodeMessageToUser(message []byte) *User {
	user := &User{}
	err := json.Unmarshal(message, user)
	if err != nil {
		log.Fatal(err)
	}
	return user
}
