/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package enum

type Visibility string

// List of Visibility
const (
	PUBLIC  Visibility = "public"
	LIMITED Visibility = "limited"
	PRIVATE Visibility = "private"
)
