on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go vet ./...
      - run: go test ./test/...
  build-publish-latest:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $CR_PAT | docker login ghcr.io -u danielmunro --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/danielmunro/otto-community-service:latest .
      - run: docker push ghcr.io/danielmunro/otto-community-service:latest
