on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to deploy"
        required: true
        type: string
jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: snap install yq
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/danielmunro/otto-community-service-consumer:${{ inputs.tag }}"' kustomize/dev/deployment-consumer.yaml
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/danielmunro/otto-community-service:${{ inputs.tag }}"' kustomize/dev/deployment-consumer.yaml
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/danielmunro/otto-community-service-consumer:${{ inputs.tag }}"' kustomize/prod/deployment-consumer.yaml
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/danielmunro/otto-community-service:${{ inputs.tag }}"' kustomize/prod/deployment-consumer.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Deploy version ${{ inputs.tag }}"
