on:
  push:
    tags:
      - '*'
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u danielmunro --password-stdin
      - run: docker build -t ghcr.io/danielmunro/otto-community-service:${{ github.ref_name }} .
      - run: docker push ghcr.io/danielmunro/otto-community-service:${{ github.ref_name }}
      - run: mv ./cmd/kafka/main.go .
      - run: docker build -t ghcr.io/danielmunro/otto-community-service-consumer:${{ github.ref_name }} .
      - run: docker push ghcr.io/danielmunro/otto-community-service-consumer:${{ github.ref_name }}
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: publish-docker-image
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: sudo snap install yq
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/danielmunro/otto-community-service-consumer:${{ github.ref_name }}"' kustomize/dev/deployment-consumer.yaml
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/danielmunro/otto-community-service:${{ github.ref_name }}"' kustomize/dev/deployment-service.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Deploy version ${{ github.ref_name }} to development"
